SGAApresentacao/Controllers/AtivosController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SCA.Apresentacao.Data;
using SCA.Apresentacao.Models;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;

namespace SCA.Apresentacao.Controllers
{
    public class AtivosController : Controller
    {

        //private readonly SCA.Apresentacao.Data.SCAApresentacaoContext _context;

        //private readonly IAtivoInterface _ativoNegocio;
        //public AtivosController(IAtivoInterface ativoNegocio)
        //{
        //    _ativoNegocio = ativoNegocio;
        //}
        //public AtivosController(SCA.Apresentacao.Data.SCAApresentacaoContext context)
        //{
        //    _context = context;
        //}

        public async Task<IActionResult> Index()
       {
            var accessToken = await HttpContext.GetTokenAsync("access_token");

            var client = new HttpClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            var content = await client.GetStringAsync("http://host.docker.internal:10000/Ativos/");
            
            var model = JsonConvert.DeserializeObject<List<Ativo>>(content);
          
            ViewBag.listaAtivosJson = JArray.Parse(content).ToString();
            
            return View(model);
        }

        public ActionResult Novo()
        {
            return View("AtivoNovo");
        }
        [HttpPost]
        public async Task<IActionResult> Novo(Ativo ativo)
        {

            var accessToken = await HttpContext.GetTokenAsync("access_token");
            
            var client = new HttpClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            var content = JsonConvert.SerializeObject(ativo);
            var httpContent = new StringContent(content, Encoding.UTF8, "application/json");
            HttpResponseMessage response = await client.PostAsync("http://host.docker.internal:10000/Ativos/", httpContent);
           
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Excluir(int id)
        {
            var accessToken = await HttpContext.GetTokenAsync("access_token");
            var client = new HttpClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            var content = await client.DeleteAsync("http://host.docker.internal:10000/Ativos/" + id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> AtivoAtualizar(Ativo ativo)
        {
            var accessToken = await HttpContext.GetTokenAsync("access_token");

            var client = new HttpClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            var content = JsonConvert.SerializeObject(ativo);
            var httpContent = new StringContent(content, Encoding.UTF8, "application/json");
            HttpResponseMessage response = await client.PostAsync("http://host.docker.internal:10000/Ativos/", httpContent);
            return RedirectToAction("Index");
        }
    }
}

SGAApresentacao/Controllers/ComplianceController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace SCA.Apresentacao.Controllers
{
    public class ComplianceController : Controller
    {
        // GET: Compliance
        public async Task<ActionResult> Index()
        {
            var accessToken = await HttpContext.GetTokenAsync("access_token");

            var client = new HttpClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            var content = await client.GetStringAsync("http://host.docker.internal:10000/Conformidade/");

            ViewBag.listaConformidadeJson = JArray.Parse(content).ToString();

            return View();
        }

        // GET: Compliance/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Compliance/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Compliance/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Compliance/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Compliance/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Compliance/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Compliance/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

SGAApresentacao/Controllers/MonitoramentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;

namespace SCA.Apresentacao.Controllers
{
    public class MonitoramentoController : Controller
    {
        // GET: Monitoramento
        public async Task<ActionResult> Index()
        {
            var accessToken = await HttpContext.GetTokenAsync("access_token");

            var client = new HttpClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            var content = await client.GetStringAsync("http://host.docker.internal:10000/Monitoramento/");

            ViewBag.listaMonitoramentoJson = JArray.Parse(content).ToString();

            return View();
        }

        // GET: Monitoramento/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Monitoramento/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Monitoramento/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Monitoramento/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Monitoramento/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Monitoramento/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Monitoramento/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

SGAApresentacao/Controllers/ProcessoMinerarioController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace SCA.Apresentacao.Controllers
{
    public class ProcessoMinerarioController : Controller
    {
        // GET: ProcessoMinerario
        public async Task<ActionResult> Index()
        {
            var accessToken = await HttpContext.GetTokenAsync("access_token");

            var client = new HttpClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            var content = await client.GetStringAsync("http://host.docker.internal:10000/ProcessoMinerario/");

            ViewBag.listaProcessoMinerarioJson = JArray.Parse(content).ToString();

            return View();
        }

        // GET: ProcessoMinerario/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ProcessoMinerario/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProcessoMinerario/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProcessoMinerario/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ProcessoMinerario/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProcessoMinerario/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ProcessoMinerario/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

SGAApresentacao/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sistema de Gestão Ambiental</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sistema de Gestão Ambiental</a>*@
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                            @*<li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ativos" asp-action="Index">Controle de Ativos</a>
                        </li>
                        <li class="nav-item disabled">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Compliance" asp-action="Index">Compliance</a>
                        </li>
                        <li class="nav-item disabled">
                            <a class="nav-link text-dark" asp-area="" asp-controller="InteligenciaNegocio" asp-action="Index">Inteligência de Negócio</a>
                        </li>
                        <li class="nav-item disabled">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Monitoramento" asp-action="Index">Monitoramento</a>
                        </li>
                        <li class="nav-item disabled">
                            <a class="nav-link text-dark " asp-area="" asp-controller="ProcessoMinerario" asp-action="Index">Processo Minerário</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark font-weight-bold" href="http://host.docker.internal:9000/Account/Logout">Sair</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SGA.Apresentacao - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>